# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9dcad8f70c67c83942fe3623a56fadf6f6d77fe7ff0b2a6a18270aa59026ba9f8fd5ae150d83d2c36d54a54930255fa6065730614f1851249e341b2ba8dd2fc

test:
  secret_key_base: a06a0539115c357708b9c10e6fd7e9c25206789895155b7c28dfdbcf6ad1ad1cb9eaa88bc8af517a08ed44808785d74ffadccede50a566cc8cf227b94d5e1a7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
